### ISSUE TITLE
feat: Unlock bikes at any distance from the station

### ISSUE THREAD

**Issue by cyberastr4l** [afonsosousah/mGira#52]
Add and option under the minimum distance to station to set it no none, infinite or disable, so that the bike can be unlocked even if far away from the station.

**Comment by ImRodry** [comment]
This would likely lead to API abuse which we do not want, what is your use case for this?

**Comment by cyberastr4l** [comment]
I was thinking in maybe unlocking a bike for a friend, or just if I want to keep location off as I'm a privacy type guy. But if it leads to API abuse I understand that you guys don't want to implement it.

**Comment by ImRodry** [comment]
Your location never leaves the app. The distance is calculated on your device and it is then used to determine if you're allowed to unlock a bike or not. We've already added the option to unlock at 75m and 100m (the official app only allows 50m) for situations where the GPS signal is weak. There have been use cases for disabling this limit entirely for when you can't enable location on your device but this is something we'd like to avoid at all costs because our intention with this app isn't to break the original system, only to make the UX better within the boundaries we deem reasonable
